-- Baseline generated from `prisma migrate diff --from-empty --to-schema-datamodel prisma/schema.prisma --script`, then extended with PostgreSQL-only constraints below.
CREATE SCHEMA IF NOT EXISTS "public";
CREATE TYPE "UserRole" AS ENUM ('CITIZEN', 'DEMO_OPERATOR');
CREATE TYPE "ParticipantRole" AS ENUM ('SELLER', 'BUYER');
CREATE TYPE "ApplicationState" AS ENUM ('DRAFT', 'SELLER_ACTION_REQUIRED', 'SELLER_VERIFIED', 'BUYER_ACTION_REQUIRED', 'BUYER_VERIFIED', 'DOCUMENTS_REQUIRED', 'READY_FOR_SUBMISSION', 'PAYMENT_REQUIRED', 'PAYMENT_PENDING', 'PAYMENT_CONFIRMED', 'PAYMENT_FAILED', 'PAYMENT_RECONCILIATION_REQUIRED', 'SUBMITTED', 'SENT_TO_RTO', 'RTO_PROCESSING', 'CORRECTION_REQUIRED', 'APPROVED', 'REJECTED', 'REGISTRY_UPDATE_COMPLETE', 'WITHDRAWAL_PENDING', 'WITHDRAWAL_REQUIRES_RTO', 'WITHDRAWN_EXTERNALLY_CONFIRMED');
CREATE TYPE "PaymentStatus" AS ENUM ('REQUESTED', 'PENDING', 'FAILED', 'CONFIRMED', 'RECONCILIATION_REQUIRED');
CREATE TYPE "PaymentEventDisposition" AS ENUM ('PENDING', 'APPLIED', 'DUPLICATE', 'STALE', 'QUARANTINED');
CREATE TYPE "IntegrationStatus" AS ENUM ('PENDING', 'PROCESSING', 'SUCCEEDED', 'FAILED', 'QUARANTINED');
CREATE TYPE "ExternalEventDisposition" AS ENUM ('PENDING', 'APPLIED', 'DUPLICATE', 'STALE', 'QUARANTINED');
CREATE TYPE "ReadinessStatus" AS ENUM ('READY_FOR_DEMO', 'BLOCKED_FOR_DEMO', 'UNKNOWN');

CREATE TABLE "User" ("id" TEXT NOT NULL, "displayName" TEXT NOT NULL, "role" "UserRole" NOT NULL DEFAULT 'CITIZEN', "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "User_pkey" PRIMARY KEY ("id"));
CREATE TABLE "UserProfile" ("id" TEXT NOT NULL, "userId" TEXT NOT NULL, "locale" TEXT NOT NULL DEFAULT 'en', CONSTRAINT "UserProfile_pkey" PRIMARY KEY ("id"));
CREATE TABLE "Session" ("id" TEXT NOT NULL, "userId" TEXT NOT NULL, "tokenHash" TEXT NOT NULL, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "expiresAt" TIMESTAMP(3) NOT NULL, "revokedAt" TIMESTAMP(3), CONSTRAINT "Session_pkey" PRIMARY KEY ("id"));
CREATE TABLE "TotpCredential" ("id" TEXT NOT NULL, "userId" TEXT NOT NULL, "encryptedSecret" TEXT NOT NULL, "encryptionIv" TEXT NOT NULL, "enrollmentState" TEXT NOT NULL DEFAULT 'NOT_ENROLLED', "lastAcceptedStep" INTEGER, "failedAttempts" INTEGER NOT NULL DEFAULT 0, "lockedUntil" TIMESTAMP(3), "enrollmentChallengeHash" TEXT, "enrollmentExpiresAt" TIMESTAMP(3), CONSTRAINT "TotpCredential_pkey" PRIMARY KEY ("id"));
CREATE TABLE "ExternalIdentityReference" ("id" TEXT NOT NULL, "userId" TEXT NOT NULL, "source" TEXT NOT NULL, "reference" TEXT NOT NULL, CONSTRAINT "ExternalIdentityReference_pkey" PRIMARY KEY ("id"));
CREATE TABLE "VehicleProjection" ("id" TEXT NOT NULL, "registrationNumber" TEXT NOT NULL, "source" TEXT NOT NULL, "externalReference" TEXT NOT NULL, "sourceVersion" TEXT, "lastSyncedAt" TIMESTAMP(3) NOT NULL, "vehicleClass" TEXT NOT NULL DEFAULT 'PRIVATE_NON_TRANSPORT', "registrationState" TEXT NOT NULL DEFAULT 'KA', CONSTRAINT "VehicleProjection_pkey" PRIMARY KEY ("id"));
CREATE TABLE "VehicleOwnership" ("id" TEXT NOT NULL, "vehicleProjectionId" TEXT NOT NULL, "ownerId" TEXT NOT NULL, "validFrom" TIMESTAMP(3) NOT NULL, "validUntil" TIMESTAMP(3), "source" TEXT NOT NULL, "externalReference" TEXT NOT NULL, "observedAt" TIMESTAMP(3) NOT NULL, "transferApplicationReference" TEXT, CONSTRAINT "VehicleOwnership_pkey" PRIMARY KEY ("id"));
CREATE TABLE "ServiceDefinition" ("id" TEXT NOT NULL, "key" TEXT NOT NULL, "version" TEXT NOT NULL, "processingMode" TEXT NOT NULL, "provenance" TEXT NOT NULL, CONSTRAINT "ServiceDefinition_pkey" PRIMARY KEY ("id"));
CREATE TABLE "ServiceRule" ("id" TEXT NOT NULL, "serviceDefinitionId" TEXT NOT NULL, "version" TEXT NOT NULL, "body" JSONB NOT NULL, CONSTRAINT "ServiceRule_pkey" PRIMARY KEY ("id"));
CREATE TABLE "Application" ("id" TEXT NOT NULL, "vehicleProjectionId" TEXT NOT NULL, "serviceDefinitionId" TEXT NOT NULL, "serviceRuleId" TEXT NOT NULL, "state" "ApplicationState" NOT NULL DEFAULT 'DRAFT', "aggregateVersion" INTEGER NOT NULL DEFAULT 0, "ruleVersion" TEXT NOT NULL, "ruleBodyHash" TEXT NOT NULL, "ruleBodySnapshot" JSONB NOT NULL, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "Application_pkey" PRIMARY KEY ("id"));
CREATE TABLE "ReadinessResult" ("id" TEXT NOT NULL, "applicationId" TEXT NOT NULL, "serviceDefinitionId" TEXT NOT NULL, "status" "ReadinessStatus" NOT NULL, "processingMode" TEXT NOT NULL, "inputs" JSONB NOT NULL, "findings" JSONB NOT NULL, "ruleBodyHash" TEXT NOT NULL, "evaluatorVersion" TEXT NOT NULL, "provenanceVersion" TEXT NOT NULL, "disclosureVersion" TEXT NOT NULL, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "ReadinessResult_pkey" PRIMARY KEY ("id"));
CREATE TABLE "SellerDeclaration" ("id" TEXT NOT NULL, "applicationId" TEXT NOT NULL, "readinessResultId" TEXT NOT NULL, "statementVersion" TEXT NOT NULL, "statementSnapshot" TEXT NOT NULL, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "SellerDeclaration_pkey" PRIMARY KEY ("id"));
CREATE TABLE "CommandReceipt" ("id" TEXT NOT NULL, "scope" TEXT NOT NULL, "actorId" TEXT NOT NULL, "command" TEXT NOT NULL, "idempotencyKey" TEXT NOT NULL, "requestHash" TEXT NOT NULL, "result" JSONB NOT NULL, "aggregateVersion" INTEGER NOT NULL, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "applicationId" TEXT, CONSTRAINT "CommandReceipt_pkey" PRIMARY KEY ("id"));
CREATE TABLE "BuyerInformationSnapshot" ("id" TEXT NOT NULL, "applicationId" TEXT NOT NULL, "version" TEXT NOT NULL, "data" JSONB NOT NULL, "documentChecklist" JSONB NOT NULL, "provenanceVersion" TEXT NOT NULL, "disclosureVersion" TEXT NOT NULL, "contentHash" TEXT NOT NULL, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "BuyerInformationSnapshot_pkey" PRIMARY KEY ("id"));
CREATE TABLE "BuyerDeclaration" ("id" TEXT NOT NULL, "applicationId" TEXT NOT NULL, "buyerInformationId" TEXT NOT NULL, "statementVersion" TEXT NOT NULL, "statementSnapshot" TEXT NOT NULL, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "BuyerDeclaration_pkey" PRIMARY KEY ("id"));
CREATE TABLE "ApplicationParticipant" ("id" TEXT NOT NULL, "applicationId" TEXT NOT NULL, "userId" TEXT NOT NULL, "role" "ParticipantRole" NOT NULL, CONSTRAINT "ApplicationParticipant_pkey" PRIMARY KEY ("id"));
CREATE TABLE "WorkflowEvent" ("id" TEXT NOT NULL, "applicationId" TEXT NOT NULL, "version" INTEGER NOT NULL, "eventType" TEXT NOT NULL, "payload" JSONB, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "WorkflowEvent_pkey" PRIMARY KEY ("id"));
CREATE TABLE "ExternalCaseReference" ("id" TEXT NOT NULL, "applicationId" TEXT NOT NULL, "source" TEXT NOT NULL, "externalReference" TEXT NOT NULL, CONSTRAINT "ExternalCaseReference_pkey" PRIMARY KEY ("id"));
CREATE TABLE "DocumentRequirementSnapshot" ("id" TEXT NOT NULL, "applicationId" TEXT NOT NULL, "participantRole" "ParticipantRole" NOT NULL, "ruleVersion" TEXT NOT NULL, "required" BOOLEAN NOT NULL, "reason" TEXT NOT NULL, CONSTRAINT "DocumentRequirementSnapshot_pkey" PRIMARY KEY ("id"));
CREATE TABLE "DocumentSubmission" ("id" TEXT NOT NULL, "requirementId" TEXT NOT NULL, "currentVersion" INTEGER NOT NULL DEFAULT 1, CONSTRAINT "DocumentSubmission_pkey" PRIMARY KEY ("id"));
CREATE TABLE "DocumentSubmissionVersion" ("id" TEXT NOT NULL, "documentSubmissionId" TEXT NOT NULL, "version" INTEGER NOT NULL, "metadata" JSONB NOT NULL, CONSTRAINT "DocumentSubmissionVersion_pkey" PRIMARY KEY ("id"));
CREATE TABLE "PricingSnapshot" ("id" TEXT NOT NULL, "applicationId" TEXT NOT NULL, "amountMinor" INTEGER NOT NULL, "currency" TEXT NOT NULL, "label" TEXT NOT NULL, "disclosureVersion" TEXT NOT NULL, "ruleVersion" TEXT NOT NULL, "contentHash" TEXT NOT NULL, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "PricingSnapshot_pkey" PRIMARY KEY ("id"));
CREATE TABLE "Payment" ("id" TEXT NOT NULL, "applicationId" TEXT NOT NULL, "status" "PaymentStatus" NOT NULL DEFAULT 'REQUESTED', "amountMinor" INTEGER NOT NULL, "currency" TEXT NOT NULL DEFAULT 'INR', "pricingSnapshotId" TEXT NOT NULL, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "Payment_pkey" PRIMARY KEY ("id"));
CREATE TABLE "PaymentAttempt" ("id" TEXT NOT NULL, "paymentId" TEXT NOT NULL, "attemptNumber" INTEGER NOT NULL, "idempotencyKey" TEXT NOT NULL, "providerReference" TEXT, "status" "PaymentStatus" NOT NULL, "sequence" INTEGER NOT NULL DEFAULT 0, "safeCode" TEXT, "requestedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "dispatchedAt" TIMESTAMP(3), "resolvedAt" TIMESTAMP(3), CONSTRAINT "PaymentAttempt_pkey" PRIMARY KEY ("id"));
CREATE TABLE "PaymentProviderEvent" ("id" TEXT NOT NULL, "paymentAttemptId" TEXT, "source" TEXT NOT NULL, "externalEventId" TEXT NOT NULL, "providerReference" TEXT NOT NULL, "kind" TEXT NOT NULL, "payloadVersion" TEXT NOT NULL, "sequence" INTEGER NOT NULL, "payload" JSONB NOT NULL, "payloadHash" TEXT NOT NULL, "disposition" "PaymentEventDisposition" NOT NULL DEFAULT 'PENDING', "receivedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "processedAt" TIMESTAMP(3), CONSTRAINT "PaymentProviderEvent_pkey" PRIMARY KEY ("id"));
CREATE TABLE "PaymentReconciliation" ("id" TEXT NOT NULL, "paymentId" TEXT NOT NULL, "status" TEXT NOT NULL, "reasonCode" TEXT NOT NULL, "resultCode" TEXT, "evidence" JSONB, "openedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "resolvedAt" TIMESTAMP(3), "triggerAttemptId" TEXT, "triggerEventId" TEXT, CONSTRAINT "PaymentReconciliation_pkey" PRIMARY KEY ("id"));
CREATE TABLE "InboxEvent" ("id" TEXT NOT NULL, "applicationId" TEXT, "source" TEXT NOT NULL, "externalEventId" TEXT NOT NULL, "externalReference" TEXT, "sequence" INTEGER NOT NULL, "payload" JSONB NOT NULL, "payloadVersion" TEXT, "kind" TEXT, "payloadHash" TEXT, "disposition" "ExternalEventDisposition" NOT NULL DEFAULT 'PENDING', "safeReason" TEXT, "receivedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "processedAt" TIMESTAMP(3), CONSTRAINT "InboxEvent_pkey" PRIMARY KEY ("id"));
CREATE TABLE "ExternalEventCursor" ("id" TEXT NOT NULL, "source" TEXT NOT NULL, "externalReference" TEXT NOT NULL, "lastAppliedSequence" INTEGER NOT NULL DEFAULT 0, "lastAppliedHash" TEXT, CONSTRAINT "ExternalEventCursor_pkey" PRIMARY KEY ("id"));
CREATE TABLE "CorrectionRequest" ("id" TEXT NOT NULL, "applicationId" TEXT NOT NULL, "sourceEventId" TEXT NOT NULL, "sequence" INTEGER NOT NULL, "reasonCode" TEXT NOT NULL, "explanation" TEXT NOT NULL, "targetRole" "ParticipantRole" NOT NULL, "status" TEXT NOT NULL DEFAULT 'OPEN', "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "resolvedAt" TIMESTAMP(3), CONSTRAINT "CorrectionRequest_pkey" PRIMARY KEY ("id"));
CREATE TABLE "CorrectionSubmission" ("id" TEXT NOT NULL, "correctionRequestId" TEXT NOT NULL, "version" INTEGER NOT NULL, "snapshot" JSONB NOT NULL, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "CorrectionSubmission_pkey" PRIMARY KEY ("id"));
CREATE TABLE "WithdrawalRequest" ("id" TEXT NOT NULL, "applicationId" TEXT NOT NULL, "version" INTEGER NOT NULL, "requesterId" TEXT NOT NULL, "status" TEXT NOT NULL DEFAULT 'OPEN', "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "resolvedAt" TIMESTAMP(3), CONSTRAINT "WithdrawalRequest_pkey" PRIMARY KEY ("id"));
CREATE TABLE "OutboxMessage" ("id" TEXT NOT NULL, "applicationId" TEXT, "kind" TEXT NOT NULL, "idempotencyKey" TEXT NOT NULL, "payload" JSONB NOT NULL, "status" "IntegrationStatus" NOT NULL DEFAULT 'PENDING', "attemptCount" INTEGER NOT NULL DEFAULT 0, "nextAttemptAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "claimedAt" TIMESTAMP(3), "leaseUntil" TIMESTAMP(3), "completedAt" TIMESTAMP(3), "safeLastErrorCode" TEXT, CONSTRAINT "OutboxMessage_pkey" PRIMARY KEY ("id"));
CREATE TABLE "ExternalStatusEvent" ("id" TEXT NOT NULL, "source" TEXT NOT NULL, "externalEventId" TEXT NOT NULL, "sequence" INTEGER NOT NULL, "payload" JSONB NOT NULL, CONSTRAINT "ExternalStatusEvent_pkey" PRIMARY KEY ("id"));
CREATE TABLE "IntegrationAttempt" ("id" TEXT NOT NULL, "provider" TEXT NOT NULL, "operation" TEXT NOT NULL, "idempotencyKey" TEXT NOT NULL, "status" "IntegrationStatus" NOT NULL, CONSTRAINT "IntegrationAttempt_pkey" PRIMARY KEY ("id"));
CREATE TABLE "Notification" ("id" TEXT NOT NULL, "userId" TEXT NOT NULL, "applicationId" TEXT, "message" TEXT NOT NULL, "href" TEXT, "dedupeKey" TEXT, "readAt" TIMESTAMP(3), CONSTRAINT "Notification_pkey" PRIMARY KEY ("id"));
CREATE TABLE "AuditEvent" ("id" TEXT NOT NULL, "applicationId" TEXT, "actorId" TEXT, "action" TEXT NOT NULL, "payload" JSONB, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "AuditEvent_pkey" PRIMARY KEY ("id"));
CREATE TABLE "OperatorAction" ("id" TEXT NOT NULL, "operatorId" TEXT NOT NULL, "action" TEXT NOT NULL, "targetId" TEXT NOT NULL, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "OperatorAction_pkey" PRIMARY KEY ("id"));

CREATE UNIQUE INDEX "UserProfile_userId_key" ON "UserProfile"("userId");
CREATE UNIQUE INDEX "TotpCredential_userId_key" ON "TotpCredential"("userId");
CREATE UNIQUE INDEX "Session_tokenHash_key" ON "Session"("tokenHash");
CREATE UNIQUE INDEX "ExternalIdentityReference_source_reference_key" ON "ExternalIdentityReference"("source", "reference");
CREATE UNIQUE INDEX "VehicleProjection_registrationNumber_key" ON "VehicleProjection"("registrationNumber");
CREATE INDEX "VehicleOwnership_vehicleProjectionId_validFrom_idx" ON "VehicleOwnership"("vehicleProjectionId", "validFrom");
CREATE UNIQUE INDEX "ServiceDefinition_key_version_key" ON "ServiceDefinition"("key", "version");
CREATE INDEX "ReadinessResult_applicationId_createdAt_idx" ON "ReadinessResult"("applicationId", "createdAt");
CREATE UNIQUE INDEX "SellerDeclaration_applicationId_key" ON "SellerDeclaration"("applicationId");
CREATE UNIQUE INDEX "SellerDeclaration_readinessResultId_key" ON "SellerDeclaration"("readinessResultId");
CREATE UNIQUE INDEX "CommandReceipt_scope_actorId_command_idempotencyKey_key" ON "CommandReceipt"("scope", "actorId", "command", "idempotencyKey");
CREATE UNIQUE INDEX "BuyerInformationSnapshot_applicationId_key" ON "BuyerInformationSnapshot"("applicationId");
CREATE UNIQUE INDEX "BuyerDeclaration_applicationId_key" ON "BuyerDeclaration"("applicationId");
CREATE UNIQUE INDEX "BuyerDeclaration_buyerInformationId_key" ON "BuyerDeclaration"("buyerInformationId");
CREATE UNIQUE INDEX "ServiceRule_serviceDefinitionId_version_key" ON "ServiceRule"("serviceDefinitionId", "version");
CREATE INDEX "Application_vehicleProjectionId_state_idx" ON "Application"("vehicleProjectionId", "state");
CREATE UNIQUE INDEX "ApplicationParticipant_applicationId_role_key" ON "ApplicationParticipant"("applicationId", "role");
CREATE UNIQUE INDEX "ApplicationParticipant_applicationId_userId_key" ON "ApplicationParticipant"("applicationId", "userId");
CREATE UNIQUE INDEX "WorkflowEvent_applicationId_version_key" ON "WorkflowEvent"("applicationId", "version");
CREATE UNIQUE INDEX "ExternalCaseReference_applicationId_key" ON "ExternalCaseReference"("applicationId");
CREATE UNIQUE INDEX "ExternalCaseReference_source_externalReference_key" ON "ExternalCaseReference"("source", "externalReference");
CREATE UNIQUE INDEX "DocumentSubmissionVersion_documentSubmissionId_version_key" ON "DocumentSubmissionVersion"("documentSubmissionId", "version");
CREATE UNIQUE INDEX "PricingSnapshot_applicationId_key" ON "PricingSnapshot"("applicationId");
CREATE UNIQUE INDEX "Payment_applicationId_key" ON "Payment"("applicationId");
CREATE UNIQUE INDEX "Payment_pricingSnapshotId_key" ON "Payment"("pricingSnapshotId");
CREATE UNIQUE INDEX "PaymentAttempt_paymentId_attemptNumber_key" ON "PaymentAttempt"("paymentId", "attemptNumber");
CREATE UNIQUE INDEX "PaymentAttempt_paymentId_idempotencyKey_key" ON "PaymentAttempt"("paymentId", "idempotencyKey");
CREATE UNIQUE INDEX "PaymentAttempt_providerReference_key" ON "PaymentAttempt"("providerReference");
CREATE UNIQUE INDEX "PaymentProviderEvent_source_externalEventId_key" ON "PaymentProviderEvent"("source", "externalEventId");
CREATE UNIQUE INDEX "InboxEvent_source_externalEventId_key" ON "InboxEvent"("source", "externalEventId");
CREATE UNIQUE INDEX "ExternalEventCursor_source_externalReference_key" ON "ExternalEventCursor"("source", "externalReference");
CREATE UNIQUE INDEX "CorrectionRequest_sourceEventId_key" ON "CorrectionRequest"("sourceEventId");
CREATE UNIQUE INDEX "CorrectionRequest_applicationId_sequence_key" ON "CorrectionRequest"("applicationId", "sequence");
CREATE UNIQUE INDEX "CorrectionSubmission_correctionRequestId_version_key" ON "CorrectionSubmission"("correctionRequestId", "version");
CREATE UNIQUE INDEX "WithdrawalRequest_applicationId_version_key" ON "WithdrawalRequest"("applicationId", "version");
CREATE UNIQUE INDEX "OutboxMessage_kind_idempotencyKey_key" ON "OutboxMessage"("kind", "idempotencyKey");
CREATE UNIQUE INDEX "ExternalStatusEvent_source_externalEventId_key" ON "ExternalStatusEvent"("source", "externalEventId");
CREATE UNIQUE INDEX "IntegrationAttempt_provider_operation_idempotencyKey_key" ON "IntegrationAttempt"("provider", "operation", "idempotencyKey");
CREATE INDEX "Notification_applicationId_idx" ON "Notification"("applicationId");
CREATE UNIQUE INDEX "Notification_dedupeKey_key" ON "Notification"("dedupeKey");

ALTER TABLE "UserProfile" ADD CONSTRAINT "UserProfile_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "Session" ADD CONSTRAINT "Session_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "TotpCredential" ADD CONSTRAINT "TotpCredential_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "ExternalIdentityReference" ADD CONSTRAINT "ExternalIdentityReference_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "VehicleOwnership" ADD CONSTRAINT "VehicleOwnership_vehicleProjectionId_fkey" FOREIGN KEY ("vehicleProjectionId") REFERENCES "VehicleProjection"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "VehicleOwnership" ADD CONSTRAINT "VehicleOwnership_ownerId_fkey" FOREIGN KEY ("ownerId") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "ServiceRule" ADD CONSTRAINT "ServiceRule_serviceDefinitionId_fkey" FOREIGN KEY ("serviceDefinitionId") REFERENCES "ServiceDefinition"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "Application" ADD CONSTRAINT "Application_vehicleProjectionId_fkey" FOREIGN KEY ("vehicleProjectionId") REFERENCES "VehicleProjection"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "Application" ADD CONSTRAINT "Application_serviceDefinitionId_fkey" FOREIGN KEY ("serviceDefinitionId") REFERENCES "ServiceDefinition"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "Application" ADD CONSTRAINT "Application_serviceRuleId_fkey" FOREIGN KEY ("serviceRuleId") REFERENCES "ServiceRule"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "ReadinessResult" ADD CONSTRAINT "ReadinessResult_applicationId_fkey" FOREIGN KEY ("applicationId") REFERENCES "Application"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "ReadinessResult" ADD CONSTRAINT "ReadinessResult_serviceDefinitionId_fkey" FOREIGN KEY ("serviceDefinitionId") REFERENCES "ServiceDefinition"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "SellerDeclaration" ADD CONSTRAINT "SellerDeclaration_applicationId_fkey" FOREIGN KEY ("applicationId") REFERENCES "Application"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "SellerDeclaration" ADD CONSTRAINT "SellerDeclaration_readinessResultId_fkey" FOREIGN KEY ("readinessResultId") REFERENCES "ReadinessResult"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "CommandReceipt" ADD CONSTRAINT "CommandReceipt_applicationId_fkey" FOREIGN KEY ("applicationId") REFERENCES "Application"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "BuyerInformationSnapshot" ADD CONSTRAINT "BuyerInformationSnapshot_applicationId_fkey" FOREIGN KEY ("applicationId") REFERENCES "Application"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "BuyerDeclaration" ADD CONSTRAINT "BuyerDeclaration_applicationId_fkey" FOREIGN KEY ("applicationId") REFERENCES "Application"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "BuyerDeclaration" ADD CONSTRAINT "BuyerDeclaration_buyerInformationId_fkey" FOREIGN KEY ("buyerInformationId") REFERENCES "BuyerInformationSnapshot"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "ApplicationParticipant" ADD CONSTRAINT "ApplicationParticipant_applicationId_fkey" FOREIGN KEY ("applicationId") REFERENCES "Application"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "ApplicationParticipant" ADD CONSTRAINT "ApplicationParticipant_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "WorkflowEvent" ADD CONSTRAINT "WorkflowEvent_applicationId_fkey" FOREIGN KEY ("applicationId") REFERENCES "Application"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "ExternalCaseReference" ADD CONSTRAINT "ExternalCaseReference_applicationId_fkey" FOREIGN KEY ("applicationId") REFERENCES "Application"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "DocumentRequirementSnapshot" ADD CONSTRAINT "DocumentRequirementSnapshot_applicationId_fkey" FOREIGN KEY ("applicationId") REFERENCES "Application"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "DocumentSubmission" ADD CONSTRAINT "DocumentSubmission_requirementId_fkey" FOREIGN KEY ("requirementId") REFERENCES "DocumentRequirementSnapshot"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "DocumentSubmissionVersion" ADD CONSTRAINT "DocumentSubmissionVersion_documentSubmissionId_fkey" FOREIGN KEY ("documentSubmissionId") REFERENCES "DocumentSubmission"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "PricingSnapshot" ADD CONSTRAINT "PricingSnapshot_applicationId_fkey" FOREIGN KEY ("applicationId") REFERENCES "Application"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "Payment" ADD CONSTRAINT "Payment_applicationId_fkey" FOREIGN KEY ("applicationId") REFERENCES "Application"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "Payment" ADD CONSTRAINT "Payment_pricingSnapshotId_fkey" FOREIGN KEY ("pricingSnapshotId") REFERENCES "PricingSnapshot"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "PaymentAttempt" ADD CONSTRAINT "PaymentAttempt_paymentId_fkey" FOREIGN KEY ("paymentId") REFERENCES "Payment"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "PaymentProviderEvent" ADD CONSTRAINT "PaymentProviderEvent_paymentAttemptId_fkey" FOREIGN KEY ("paymentAttemptId") REFERENCES "PaymentAttempt"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "PaymentReconciliation" ADD CONSTRAINT "PaymentReconciliation_paymentId_fkey" FOREIGN KEY ("paymentId") REFERENCES "Payment"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "InboxEvent" ADD CONSTRAINT "InboxEvent_applicationId_fkey" FOREIGN KEY ("applicationId") REFERENCES "Application"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "CorrectionRequest" ADD CONSTRAINT "CorrectionRequest_applicationId_fkey" FOREIGN KEY ("applicationId") REFERENCES "Application"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "CorrectionSubmission" ADD CONSTRAINT "CorrectionSubmission_correctionRequestId_fkey" FOREIGN KEY ("correctionRequestId") REFERENCES "CorrectionRequest"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "WithdrawalRequest" ADD CONSTRAINT "WithdrawalRequest_applicationId_fkey" FOREIGN KEY ("applicationId") REFERENCES "Application"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "OutboxMessage" ADD CONSTRAINT "OutboxMessage_applicationId_fkey" FOREIGN KEY ("applicationId") REFERENCES "Application"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "Notification" ADD CONSTRAINT "Notification_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "Notification" ADD CONSTRAINT "Notification_applicationId_fkey" FOREIGN KEY ("applicationId") REFERENCES "Application"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "AuditEvent" ADD CONSTRAINT "AuditEvent_applicationId_fkey" FOREIGN KEY ("applicationId") REFERENCES "Application"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "AuditEvent" ADD CONSTRAINT "AuditEvent_actorId_fkey" FOREIGN KEY ("actorId") REFERENCES "User"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "OperatorAction" ADD CONSTRAINT "OperatorAction_operatorId_fkey" FOREIGN KEY ("operatorId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- PostgreSQL-only constraints deliberately appended to Prisma's baseline SQL.
CREATE EXTENSION IF NOT EXISTS btree_gist;
ALTER TABLE "VehicleOwnership" ADD CONSTRAINT "vehicle_ownership_valid_interval" CHECK ("validUntil" IS NULL OR "validUntil" > "validFrom");
ALTER TABLE "VehicleOwnership" ADD CONSTRAINT "vehicle_ownership_non_overlapping" EXCLUDE USING gist ("vehicleProjectionId" WITH =, tsrange("validFrom", "validUntil", '[)') WITH &&);
CREATE UNIQUE INDEX "one_active_transfer_per_vehicle" ON "Application" ("vehicleProjectionId") WHERE "state" NOT IN ('REJECTED', 'REGISTRY_UPDATE_COMPLETE', 'WITHDRAWN_EXTERNALLY_CONFIRMED');
CREATE UNIQUE INDEX "one_confirmed_attempt_per_payment" ON "PaymentAttempt" ("paymentId") WHERE "status" = 'CONFIRMED';
CREATE UNIQUE INDEX "one_unresolved_attempt_per_payment" ON "PaymentAttempt" ("paymentId") WHERE "status" IN ('REQUESTED', 'PENDING', 'RECONCILIATION_REQUIRED');
CREATE UNIQUE INDEX "one_open_reconciliation_per_payment" ON "PaymentReconciliation" ("paymentId") WHERE "status" = 'OPEN';
CREATE INDEX "OperatorAction_operatorId_action_createdAt_idx" ON "OperatorAction"("operatorId", "action", "createdAt");
