import { cookies } from "next/headers";
import { localeFrom, routeText } from "@/src/i18n";
import Link from "next/link";
import { serviceCategories } from "@/src/service-catalog";

export default async function Home() {
  const t = routeText[localeFrom((await cookies()).get("moveka_locale")?.value)];
  return <div className="home-shell">
    <section className="hero-section"><div className="hero-copy"><p className="eyebrow">A simpler way through vehicle services</p><h1>Move your vehicle paperwork forward, without the confusion.</h1><p className="hero-lede">Understand the journey, prepare each participant, and track every hand-off in one calm, accessible workspace.</p><div className="hero-actions"><Link className="button-link" href="/auth/register">Try the demo <span aria-hidden>→</span></Link><Link className="button-link secondary" href="/services">Explore 21 services</Link></div><div className="trust-row"><span>✓ Sample data only</span><span>✓ English + Kannada</span><span>✓ Mobile friendly</span></div></div><div className="hero-panel"><div className="panel-glow" /><p className="panel-label">Find services for a vehicle</p><h2>Start with the registration number</h2><form action="/services" className="vehicle-search"><label htmlFor="vehicle"><span>Registration number</span><div><input id="vehicle" name="vehicle" defaultValue="KA01AB1234" maxLength={10} aria-describedby="vehicle-help" /><button type="submit">Find services</button></div></label></form><p id="vehicle-help" className="input-help"><span aria-hidden>i</span> Use <strong>KA01AB1234</strong> for this demo.</p><div className="vehicle-preview"><span className="vehicle-badge" aria-hidden>KA</span><div><strong>KA01AB1234</strong><small>Private non-transport · Bengaluru</small></div><span className="verified-chip">Demo vehicle</span></div></div></section>
    <section className="home-section"><div className="section-heading"><div><p className="section-kicker">Service catalogue</p><h2>What do you need to do?</h2><p>Start with plain language. MoveKA maps it to the right service journey.</p></div><Link className="text-link" href="/services">Browse all services <span aria-hidden>→</span></Link></div><div className="category-grid">{serviceCategories.map((category, index) => <Link href={`/services?category=${encodeURIComponent(category.name)}`} className={`category-card category-${index + 1}`} key={category.name}><span className="category-icon" aria-hidden>{category.icon}</span><div><strong>{category.name}</strong><p>{category.description}</p></div><span className="round-arrow" aria-hidden>→</span></Link>)}</div></section>
    <section className="home-section feature-band"><div><p className="section-kicker light">Complete journey</p><h2>Transfer ownership, together.</h2><p>The seller and buyer each get a clear workspace. Progress is saved and every next step is easy to find.</p><Link className="button-link light-button" href="/services/transfer-ownership-seller">See how it works <span aria-hidden>→</span></Link></div><div className="journey-card"><div className="journey-person"><span className="avatar blue">AR</span><div><strong>Ananya</strong><small>Seller · complete</small></div><span className="journey-check">✓</span></div><div className="journey-line"><span /></div><div className="journey-person"><span className="avatar violet">RS</span><div><strong>Rahul</strong><small>Buyer · your turn</small></div><span className="journey-next">→</span></div><div className="journey-summary"><span>Current step</span><strong>Buyer review and acceptance</strong><small>Progress is saved automatically</small></div></div></section>
    <section className="home-section"><div className="section-heading"><div><p className="section-kicker">Built around people</p><h2>Clarity at every step.</h2></div></div><div className="benefit-grid"><article><span className="benefit-number">01</span><h3>Know what comes next</h3><p>See the journey, roles and external hand-offs before you begin.</p></article><article><span className="benefit-number">02</span><h3>Stop and resume safely</h3><p>Return to a dashboard that shows the current state and next action.</p></article><article><span className="benefit-number">03</span><h3>No false promises</h3><p>Government verification, fees and decisions are always shown as external.</p></article></div></section>
    <section className="home-section final-cta"><div><p className="eyebrow">Ready to explore?</p><h2>{t.homeTitle}</h2><p>{t.homeBody}</p></div><div><Link className="button-link" href="/auth/register">Choose a demo role</Link><Link className="text-link" href="/auth/sign-in">Sign in to the demo</Link></div></section>
  </div>;
}
