"use server";
import { redirect } from "next/navigation";
import { requireCurrentSession } from "@/src/identity/access";
import { requireDemoMode } from "@/src/identity/config";
import { SellerTransferService } from "@/src/domain/seller-transfer";
import { prisma } from "@/src/lib/prisma";
import { sellerErrorCode } from "@/src/domain/seller-errors";
import { BuyerFlowService } from "@/src/domain/buyer-flow";
import { currentWorkspaceForUser, requireCurrentWorkspaceApplication } from "@/src/workspace/context";
const service = new SellerTransferService(prisma);
const buyerFlow = new BuyerFlowService(prisma);
export async function inviteBuyer(formData: FormData) { const applicationId = String(formData.get("applicationId") ?? ""); try { requireDemoMode(); const session = await requireCurrentSession(); await requireCurrentWorkspaceApplication(applicationId, session.userId); await buyerFlow.inviteBuyer(session.userId, { applicationId, idempotencyKey: String(formData.get("intentKey") ?? ""), expectedVersion: Number(formData.get("expectedVersion")) }); } catch (error) { redirect(`/seller?application=${applicationId}&error=${sellerErrorCode(error)}`); } redirect(`/seller?application=${applicationId}`); }
export async function createSellerDraft(formData: FormData) { let result: { applicationId: string }; try { requireDemoMode(); const session = await requireCurrentSession(); const workspace = await currentWorkspaceForUser(session.userId); const vehicle = workspace ? await prisma.vehicleProjection.findFirst({ where: { workspaceId: workspace.id, registrationNumber: "KA01AB1234" }, select: { id: true } }) : null; if (!workspace || !vehicle) throw new Error("Synthetic vehicle fixture is unavailable."); result = await service.createDraft(session.userId, { workspaceId: workspace.id, vehicleId: vehicle.id, idempotencyKey: String(formData.get("intentKey") ?? "") }) as { applicationId: string }; } catch (error) { redirect(`/seller?error=${sellerErrorCode(error)}`); } redirect(`/seller?application=${result!.applicationId}`); }
export async function evaluateSellerReadiness(formData: FormData) { const applicationId = String(formData.get("applicationId") ?? ""); try { requireDemoMode(); const session = await requireCurrentSession(); await requireCurrentWorkspaceApplication(applicationId, session.userId); await service.evaluateReadiness(session.userId, { applicationId, idempotencyKey: String(formData.get("intentKey") ?? ""), expectedVersion: Number(formData.get("expectedVersion")) }); } catch (error) { redirect(`/seller?application=${applicationId}&error=${sellerErrorCode(error)}`); } redirect(`/seller?application=${applicationId}`); }
export async function completeSeller(formData: FormData) { const applicationId = String(formData.get("applicationId") ?? ""); try { requireDemoMode(); const session = await requireCurrentSession(); await requireCurrentWorkspaceApplication(applicationId, session.userId); const readinessResultId = String(formData.get("readinessResultId") ?? ""); await service.completeSellerDeclaration(session.userId, { applicationId, readinessResultId, idempotencyKey: String(formData.get("intentKey") ?? ""), statementVersion: "seller-prototype-v1" }); } catch (error) { redirect(`/seller?application=${applicationId}&error=${sellerErrorCode(error)}`); } redirect(`/seller?application=${applicationId}`); }
