"use server";
import { redirect } from "next/navigation";
import { requireCurrentSession } from "@/src/identity/access";
import { requireDemoMode } from "@/src/identity/config";
import { PaymentFlowService } from "@/src/domain/payment-flow";
import { sellerErrorCode } from "@/src/domain/seller-errors";
import { prisma } from "@/src/lib/prisma";
import { requireCurrentWorkspaceApplication } from "@/src/workspace/context";
const service = new PaymentFlowService(prisma);
export async function createPayment(formData: FormData) { const applicationId = String(formData.get("applicationId") ?? ""); try { requireDemoMode(); const session = await requireCurrentSession(); await requireCurrentWorkspaceApplication(applicationId, session.userId); await service.createPayment(session.userId, { applicationId, idempotencyKey: String(formData.get("intentKey") ?? ""), expectedVersion: Number(formData.get("expectedVersion")) }); } catch (error) { redirect(`/buyer/payment?application=${applicationId}&error=${sellerErrorCode(error)}`); } redirect(`/buyer/payment?application=${applicationId}`); }
export async function initiatePayment(formData: FormData) { const applicationId = String(formData.get("applicationId") ?? ""); try { requireDemoMode(); const session = await requireCurrentSession(); await requireCurrentWorkspaceApplication(applicationId, session.userId); await service.initiateAttempt(session.userId, { applicationId, idempotencyKey: String(formData.get("intentKey") ?? ""), expectedVersion: Number(formData.get("expectedVersion")) }); await service.dispatchOwnedPendingOutbox(session.userId, applicationId); } catch (error) { redirect(`/buyer/payment?application=${applicationId}&error=${sellerErrorCode(error)}`); } redirect(`/buyer/payment?application=${applicationId}`); }
export async function checkPaymentStatus(formData: FormData) { const applicationId = String(formData.get("applicationId") ?? ""); try { requireDemoMode(); const session = await requireCurrentSession(); await requireCurrentWorkspaceApplication(applicationId, session.userId); await service.checkPersistedStatus(session.userId, { applicationId, idempotencyKey: String(formData.get("intentKey") ?? ""), expectedVersion: Number(formData.get("expectedVersion")) }); } catch (error) { redirect(`/buyer/payment?application=${applicationId}&error=${sellerErrorCode(error)}`); } redirect(`/buyer/payment?application=${applicationId}`); }
export async function completeDemoPayment(formData: FormData) { const applicationId=String(formData.get("applicationId")??""); try { requireDemoMode(); const session=await requireCurrentSession(); await requireCurrentWorkspaceApplication(applicationId, session.userId); await service.completeSyntheticDemoPayment(session.userId,{applicationId,idempotencyKey:String(formData.get("intentKey")??""),expectedVersion:Number(formData.get("expectedVersion"))}); } catch(error){redirect(`/buyer/payment?application=${applicationId}&error=${sellerErrorCode(error)}`);} redirect(`/buyer/payment?application=${applicationId}`); }
