import type { Locale } from "./i18n";
export const caseText={en:{title:"Track your application",none:"No application is available.",reference:"Application reference",unack:"Being created",notOfficial:"",correction:"More information is needed.",correctionReason:"Reason",correctionDetails:"What to check",correctionTarget:"Action for",seller:"Seller",buyer:"Buyer",confirm:"Confirm update",withdraw:"Request withdrawal",manual:"Please contact the RTO for help with withdrawal at this stage.",timeline:"Application history",payment:"Continue to payment",back:"Back to your workspace",external:"Status update",recorded:"Application updated",step:"Step"},kn:{title:"ನಿಮ್ಮ ಅರ್ಜಿಯನ್ನು ಗಮನಿಸಿ",none:"ಯಾವುದೇ ಅರ್ಜಿ ಲಭ್ಯವಿಲ್ಲ.",reference:"ಅರ್ಜಿ ಉಲ್ಲೇಖ",unack:"ರಚಿಸಲಾಗುತ್ತಿದೆ",notOfficial:"",correction:"ಹೆಚ್ಚಿನ ಮಾಹಿತಿ ಅಗತ್ಯ.",correctionReason:"ಕಾರಣ",correctionDetails:"ಪರಿಶೀಲಿಸಬೇಕಾದ ವಿಷಯ",correctionTarget:"ಕ್ರಮ ಕೈಗೊಳ್ಳುವವರು",seller:"ಮಾರಾಟಗಾರ",buyer:"ಖರೀದಿದಾರ",confirm:"ನವೀಕರಣ ದೃಢೀಕರಿಸಿ",withdraw:"ಹಿಂಪಡೆಯಲು ಕೋರಿರಿ",manual:"ಈ ಹಂತದಲ್ಲಿ ಹಿಂಪಡೆಯಲು RTO ಸಹಾಯ ಪಡೆಯಿರಿ.",timeline:"ಅರ್ಜಿಯ ಇತಿಹಾಸ",payment:"ಪಾವತಿಗೆ ಮುಂದುವರಿಯಿರಿ",back:"ನಿಮ್ಮ ಕಾರ್ಯಸ್ಥಳಕ್ಕೆ ಹಿಂತಿರುಗಿ",external:"ಸ್ಥಿತಿ ನವೀಕರಣ",recorded:"ಅರ್ಜಿ ನವೀಕರಿಸಲಾಗಿದೆ",step:"ಹಂತ"}} as const;
const eventLabels={
  en:{INWARDED:"Application review started",CORRECTION_REQUESTED:"More information requested",CORRECTION_SUBMITTED:"Information sent",CORRECTION_ACKNOWLEDGED:"Information received",APPROVED:"Application approved",REJECTED:"Application not approved",REGISTRY_UPDATE_COMPLETED:"Ownership transfer completed",WITHDRAWAL_REQUESTED:"Withdrawal requested",WITHDRAWAL_CONFIRMED:"Application withdrawn",APPLICATION_SUBMITTED:"Application submitted",GOVERNMENT_CASE_ACKNOWLEDGED:"Application received"},
  kn:{INWARDED:"ಸಿಂಥೆಟಿಕ್ ಪ್ರಕರಣ ಮಾಕ್ ಪ್ರಕ್ರಿಯೆಗೆ ಪ್ರವೇಶಿಸಿದೆ",CORRECTION_REQUESTED:"ಸಿಂಥೆಟಿಕ್ ತಿದ್ದುಪಡಿ ಕೋರಲಾಗಿದೆ",CORRECTION_SUBMITTED:"ಸಿಂಥೆಟಿಕ್ ತಿದ್ದುಪಡಿ ಕಳುಹಿಸಲಾಗಿದೆ",CORRECTION_ACKNOWLEDGED:"ಸಿಂಥೆಟಿಕ್ ತಿದ್ದುಪಡಿ ಸ್ವೀಕರಿಸಲಾಗಿದೆ",APPROVED:"ಸಿಂಥೆಟಿಕ್ ಪರಿಶೀಲನೆ ಅನುಮೋದಿಸಲಾಗಿದೆ",REJECTED:"ಸಿಂಥೆಟಿಕ್ ಪರಿಶೀಲನೆ ತಿರಸ್ಕರಿಸಲಾಗಿದೆ",REGISTRY_UPDATE_COMPLETED:"ಸಿಂಥೆಟಿಕ್ ರಿಜಿಸ್ಟ್ರಿ ನವೀಕರಣ ಪೂರ್ಣವಾಗಿದೆ",WITHDRAWAL_REQUESTED:"ಸಿಂಥೆಟಿಕ್ ಹಿಂಪಡೆಯುವಿಕೆ ಕೋರಲಾಗಿದೆ",WITHDRAWAL_CONFIRMED:"ಸಿಂಥೆಟಿಕ್ ಹಿಂಪಡೆಯುವಿಕೆ ದೃಢವಾಗಿದೆ",APPLICATION_SUBMITTED:"ಸಿಂಥೆಟಿಕ್ ಅರ್ಜಿ ಸಲ್ಲಿಸಲಾಗಿದೆ",GOVERNMENT_CASE_ACKNOWLEDGED:"ಸಿಂಥೆಟಿಕ್ ಪ್ರಕರಣ ಸ್ವೀಕೃತಿ ದಾಖಲಾಗಿದೆ"}
} as const;
export function eventLabel(locale:Locale,event:string){const normalized=event.startsWith("RTO_")?event.slice(4):event;return eventLabels[locale][normalized as keyof typeof eventLabels.en]??caseText[locale].recorded;}
export function eventDetail(locale:Locale,event:string,payload:unknown){if(event!=="REJECTED"||!payload||typeof payload!=="object")return null;const explanation=(payload as {explanation?:unknown}).explanation;return typeof explanation==="string"&&explanation.length<=240?`${correctionReasonLabel(locale,"SYNTHETIC_REVIEW_REJECTED")}: ${explanation}`:null;}
export function correctionReasonLabel(locale:Locale,code:string){if(code==="SYNTHETIC_CORRECTION_REQUIRED")return locale==="kn"?"ಸಿಂಥೆಟಿಕ್ ತಿದ್ದುಪಡಿ ಅಗತ್ಯ":"Synthetic correction required";if(code==="SYNTHETIC_REVIEW_REJECTED")return locale==="kn"?"ಸಿಂಥೆಟಿಕ್ ಪರಿಶೀಲನೆ ತಿರಸ್ಕರಿಸಲಾಗಿದೆ":"Synthetic review rejected";return locale==="kn"?"ಸಿಂಥೆಟಿಕ್ ಪರಿಶೀಲನೆ ಅಗತ್ಯ":"Synthetic review required";}
export function correctionExplanation(locale:Locale,code:string){if(code==="SYNTHETIC_CORRECTION_REQUIRED")return locale==="kn"?"ಸಿಂಥೆಟಿಕ್ ತಿದ್ದುಪಡಿಯನ್ನು ಪರಿಶೀಲಿಸಿ ಮತ್ತು ದೃಢೀಕರಿಸಿ.":"Review and confirm the synthetic correction.";return locale==="kn"?"ಈ ಸಿಂಥೆಟಿಕ್ ವಿನಂತಿಯನ್ನು ಪರಿಶೀಲಿಸಿ.":"Review this synthetic request.";}
