export const locales = ["en", "kn"] as const;
export type Locale = typeof locales[number];
export const dictionary = {
  en: { skip: "Skip to main content", language: "Language", english: "English", kannada: "Kannada", prototype: "Demo prototype", unavailable: "This demo feature is unavailable.", working: "Working…", synthetic: "Sample data only · Not a government website" },
  kn: { skip: "ಮುಖ್ಯ ವಿಷಯಕ್ಕೆ ತೆರಳಿ", language: "ಭಾಷೆ", english: "English", kannada: "ಕನ್ನಡ", prototype: "ಡೆಮೊ ಮಾದರಿ", unavailable: "ಈ ಡೆಮೊ ವೈಶಿಷ್ಟ್ಯ ಲಭ್ಯವಿಲ್ಲ.", working: "ಕಾರ್ಯನಿರ್ವಹಿಸುತ್ತಿದೆ…", synthetic: "ಮಾದರಿ ಮಾಹಿತಿ ಮಾತ್ರ · ಸರ್ಕಾರಿ ಜಾಲತಾಣವಲ್ಲ" },
} as const;
export function localeFrom(value?: string): Locale { return value === "kn" ? "kn" : "en"; }
export const friendlyState = { en: { DRAFT:"Not started", SELLER_ACTION_REQUIRED:"Seller details needed", SELLER_VERIFIED:"Seller step complete", BUYER_ACTION_REQUIRED:"Buyer review needed", BUYER_VERIFIED:"Buyer step complete", PAYMENT_REQUIRED:"Payment step needed", PAYMENT_PENDING:"Payment step needed", PAYMENT_FAILED:"Payment step needed", PAYMENT_CONFIRMED:"Payment step complete", PAYMENT_RECONCILIATION_REQUIRED:"Payment step needed", SUBMITTED:"Application submitted", SENT_TO_RTO:"Application received", RTO_PROCESSING:"Under review", CORRECTION_REQUIRED:"More information needed", APPROVED:"Approved", REJECTED:"Not approved", REGISTRY_UPDATE_COMPLETE:"Transfer complete", WITHDRAWAL_PENDING:"Withdrawal requested", WITHDRAWAL_REQUIRES_RTO:"Contact the RTO", WITHDRAWN_EXTERNALLY_CONFIRMED:"Application withdrawn" }, kn: { DRAFT:"ಪ್ರಾರಂಭವಾಗಿಲ್ಲ", SELLER_ACTION_REQUIRED:"ಮಾರಾಟಗಾರರ ವಿವರಗಳು ಅಗತ್ಯ", SELLER_VERIFIED:"ಮಾರಾಟಗಾರರ ಹಂತ ಪೂರ್ಣ", BUYER_ACTION_REQUIRED:"ಖರೀದಿದಾರರ ಪರಿಶೀಲನೆ ಅಗತ್ಯ", BUYER_VERIFIED:"ಖರೀದಿದಾರರ ಹಂತ ಪೂರ್ಣ", PAYMENT_REQUIRED:"ಪಾವತಿ ಹಂತ ಅಗತ್ಯ", PAYMENT_PENDING:"ಪಾವತಿ ಹಂತ ಅಗತ್ಯ", PAYMENT_FAILED:"ಪಾವತಿ ಹಂತ ಅಗತ್ಯ", PAYMENT_CONFIRMED:"ಪಾವತಿ ಹಂತ ಪೂರ್ಣ", PAYMENT_RECONCILIATION_REQUIRED:"ಪಾವತಿ ಹಂತ ಅಗತ್ಯ", SUBMITTED:"ಅರ್ಜಿ ಸಲ್ಲಿಸಲಾಗಿದೆ", SENT_TO_RTO:"ಅರ್ಜಿ ಸ್ವೀಕರಿಸಲಾಗಿದೆ", RTO_PROCESSING:"ಪರಿಶೀಲನೆಯಲ್ಲಿದೆ", CORRECTION_REQUIRED:"ಹೆಚ್ಚಿನ ಮಾಹಿತಿ ಅಗತ್ಯ", APPROVED:"ಅನುಮೋದಿಸಲಾಗಿದೆ", REJECTED:"ಅನುಮೋದಿಸಲಾಗಿಲ್ಲ", REGISTRY_UPDATE_COMPLETE:"ವರ್ಗಾವಣೆ ಪೂರ್ಣ", WITHDRAWAL_PENDING:"ಹಿಂಪಡೆಯಲು ಕೋರಲಾಗಿದೆ", WITHDRAWAL_REQUIRES_RTO:"RTO ಸಂಪರ್ಕಿಸಿ", WITHDRAWN_EXTERNALLY_CONFIRMED:"ಅರ್ಜಿ ಹಿಂಪಡೆಯಲಾಗಿದೆ" } } as const;
export function stateLabel(locale: Locale, state: string) { return friendlyState[locale][state as keyof typeof friendlyState.en] ?? (locale === "kn" ? "ಸ್ಥಿತಿ ಲಭ್ಯವಿಲ್ಲ" : "Status unavailable"); }
export const sellerText={en:{title:"Transfer your vehicle",status:"Current status",start:"Start ownership transfer",readiness:"Check vehicle details",case:"Track application",code:"Authenticator code",declare:"Confirm and continue",statement:"I have reviewed the vehicle details and want to continue with this transfer.",buyerWaits:"Complete your step, then invite Rahul to review the transfer.",invite:"Send to Rahul",findings:"Vehicle check",provenance:"Source",ready:"The sample vehicle is ready to continue.",handoff:"Your step is complete. Switch to Rahul's account to continue as the buyer.",switchAccount:"Switch account"},kn:{title:"ವಾಹನ ವರ್ಗಾವಣೆ",status:"ಪ್ರಸ್ತುತ ಸ್ಥಿತಿ",start:"ಮಾಲೀಕತ್ವ ವರ್ಗಾವಣೆ ಪ್ರಾರಂಭಿಸಿ",readiness:"ವಾಹನದ ವಿವರ ಪರಿಶೀಲಿಸಿ",case:"ಅರ್ಜಿ ಗಮನಿಸಿ",code:"ದೃಢೀಕರಣ ಕೋಡ್",declare:"ದೃಢೀಕರಿಸಿ ಮುಂದುವರಿಯಿರಿ",statement:"ನಾನು ವಾಹನದ ವಿವರಗಳನ್ನು ಪರಿಶೀಲಿಸಿದ್ದೇನೆ ಮತ್ತು ವರ್ಗಾವಣೆಯನ್ನು ಮುಂದುವರಿಸಲು ಬಯಸುತ್ತೇನೆ.",buyerWaits:"ನಿಮ್ಮ ಹಂತ ಪೂರ್ಣಗೊಳಿಸಿ, ನಂತರ Rahul ಗೆ ಕಳುಹಿಸಿ.",invite:"Rahul ಗೆ ಕಳುಹಿಸಿ",findings:"ವಾಹನ ಪರಿಶೀಲನೆ",provenance:"ಮೂಲ",ready:"ಮಾದರಿ ವಾಹನ ಮುಂದುವರಿಯಲು ಸಿದ್ಧವಾಗಿದೆ.",handoff:"ನಿಮ್ಮ ಹಂತ ಪೂರ್ಣವಾಗಿದೆ. ಖರೀದಿದಾರನಾಗಿ ಮುಂದುವರಿಸಲು Rahul ಖಾತೆಗೆ ಬದಲಿಸಿ.",switchAccount:"ಖಾತೆ ಬದಲಿಸಿ"}} as const;
export function findingLabel(locale:Locale, code:string) { const values={SYNTHETIC_SCENARIO_READY:sellerText[locale].ready,RULE_UNAVAILABLE:locale==="kn"?"ಸಿಂಥೆಟಿಕ್ ನಿಯಮ ಲಭ್ಯವಿಲ್ಲ.":"Synthetic rule configuration is unavailable.",PROJECTION_UNKNOWN:locale==="kn"?"ಸಿಂಥೆಟಿಕ್ ಪ್ರಕ್ಷೇಪಣ ಲಭ್ಯವಿಲ್ಲ.":"Synthetic projection is unavailable.",NOT_SYNTHETIC_OWNER:locale==="kn"?"ಈ ಖಾತೆಯು ಸಿಂಥೆಟಿಕ್ ಮಾಲೀಕವಲ್ಲ.":"This account is not the synthetic owner."} as Record<string,string>; return values[code]??(locale==="kn"?"ಅಪರಿಚಿತ ಸಿಂಥೆಟಿಕ್ ಕಂಡುಬಂದ ಮಾಹಿತಿ.":"Unknown synthetic finding."); }
export const routeText = {
 en: { homeTitle:"Vehicle services, made easier.", homeLead:"A simpler citizen experience", homeBody:"Understand each step and complete the ownership-transfer demo from start to finish.", helper:"Choose an account", helperLead:"Switch between the seller and buyer roles.", seller:"Continue as Ananya Rao — seller", buyer:"Continue as Rahul Shetty — buyer", operator:"Internal demo tools", operatorLead:"Not part of the citizen journey.", operatorBootstrapHelp:"A local access token is required.", operatorBootstrapLabel:"Access token", operatorUse:"Open internal demo tools", signIn:"Sign in", account:"Demo account", code:"Authenticator code", submit:"Sign in", switch:"Switch account", enroll:"Set up secure sign-in", choose:"Choose an account first", openHelper:"Choose an account", scan:"Scan this QR code now. It is shown only during setup; do not share it.", qrAlt:"Authenticator setup QR code", verify:"Verify and sign in", signed:"You are signed in", signedAs:"Your account is ready.", workspace:"Open dashboard", signout:"Sign out", case:"Track your application", unavailable:"Demo unavailable", disabled:"This feature is unavailable because demo mode is off." },
 kn: { homeTitle:"ಸುರಕ್ಷಿತವಾಗಿ ತೋರಿಸಲಾದ ಸಾರಿಗೆ ಸೇವಾ ಸಮನ್ವಯ.", homeLead:"ಸ್ವತಂತ್ರ ಮಾದರಿ — ಇದು ಅಧಿಕೃತ ಸೇವೆಯಲ್ಲ", homeBody:"ಇಲ್ಲಿನ ಎಲ್ಲಾ ಮಾಹಿತಿ ಮತ್ತು ಹೊರಗಿನ ಫಲಿತಾಂಶಗಳು ಸಿಂಥೆಟಿಕ್ ಮತ್ತು ಅಧಿಕೃತವಲ್ಲ.", helper:"ಡೆಮೊ ಖಾತೆ ಸಹಾಯಕ", helperLead:"ಈ ಸಹಾಯಕವು ನಿಶ್ಚಿತ ಸಿಂಥೆಟಿಕ್ ಮಾದರಿ ಖಾತೆಗಳ ನಡುವೆ ಮಾತ್ರ ಬದಲಿಸುತ್ತದೆ.", seller:"Ananya Rao — ಸಿಂಥೆಟಿಕ್ ಮಾರಾಟಗಾರ ಬಳಸಿ", buyer:"Rahul Shetty — ಸಿಂಥೆಟಿಕ್ ಖರೀದಿದಾರ ಬಳಸಿ", operator:"ಸಿಂಥೆಟಿಕ್ ಆಂತರಿಕ ನಿರ್ವಾಹಕ", operatorLead:"ಈ ಪ್ರತ್ಯೇಕ ಮಾದರಿ ಖಾತೆಯು ಮಾರಾಟಗಾರ, ಖರೀದಿದಾರ, RTO ಅಥವಾ ಸರ್ಕಾರಿ ಖಾತೆಯಲ್ಲ.", operatorBootstrapHelp:"ಸ್ಥಳೀಯ ಬೂಟ್‌ಸ್ಟ್ರ್ಯಾಪ್ ಟೋಕನ್ ಅಗತ್ಯ. ಇದನ್ನು ಒಮ್ಮೆ ಪರಿಶೀಲಿಸಲಾಗುತ್ತದೆ ಮತ್ತು ಸಂಗ್ರಹಿಸಲಾಗುವುದಿಲ್ಲ.", operatorBootstrapLabel:"ಸ್ಥಳೀಯ ನಿರ್ವಾಹಕ ಬೂಟ್‌ಸ್ಟ್ರ್ಯಾಪ್ ಟೋಕನ್", operatorUse:"Demo Operator — ಸಿಂಥೆಟಿಕ್ ಆಂತರಿಕ ಖಾತೆ ಬಳಸಿ", signIn:"ಮಾದರಿ ಖಾತೆಗೆ ಸೈನ್ ಇನ್", account:"ಸಿಂಥೆಟಿಕ್ ಡೆಮೊ ಖಾತೆ", code:"ದೃಢೀಕರಣ ಕೋಡ್", submit:"ಸೈನ್ ಇನ್", switch:"ಸಿಂಥೆಟಿಕ್ ಡೆಮೊ ಖಾತೆ ಬದಲಿಸಿ", enroll:"ಮಾದರಿ ದೃಢೀಕರಣ ಹೊಂದಿಸಿ", choose:"ಮೊದಲು ಡೆಮೊ ಖಾತೆ ಆಯ್ಕೆಮಾಡಿ", openHelper:"ಡೆಮೊ ಖಾತೆ ಸಹಾಯಕ ತೆರೆಯಿರಿ", scan:"ಈ QR ಕೋಡ್ ಅನ್ನು ಈಗ ಸ್ಕ್ಯಾನ್ ಮಾಡಿ. ಇದು ನೋಂದಣಿಗೆ ಮಾತ್ರ; ಹಂಚಿಕೊಳ್ಳಬೇಡಿ.", qrAlt:"ಈ ಸಿಂಥೆಟಿಕ್ ಮಾದರಿ ಖಾತೆಯ ದೃಢೀಕರಣ ನೋಂದಣಿ QR ಕೋಡ್", verify:"ಪರಿಶೀಲಿಸಿ ಮತ್ತು ಸೈನ್ ಇನ್", signed:"ಮಾದರಿ ಖಾತೆ ಸೈನ್ ಇನ್ ಆಗಿದೆ", signedAs:"ನೀವು ಸಿಂಥೆಟಿಕ್ ಮಾದರಿ ಖಾತೆಗೆ ಸೈನ್ ಇನ್ ಆಗಿದ್ದೀರಿ.", workspace:"ಸಿಂಥೆಟಿಕ್ ಕಾರ್ಯಸ್ಥಳ ತೆರೆಯಿರಿ", signout:"ಸೈನ್ ಔಟ್", case:"ನಿಮ್ಮ ಸಿಂಥೆಟಿಕ್ ಪ್ರಕರಣ ಸ್ಥಿತಿ ತೆರೆಯಿರಿ", unavailable:"ಮಾದರಿ ಡೆಮೊ ಲಭ್ಯವಿಲ್ಲ", disabled:"ಡೆಮೊ ಮೋಡ್ ಆಫ್ ಆಗಿರುವುದರಿಂದ ಈ ಸಿಂಥೆಟಿಕ್ ಮಾದರಿ ವೈಶಿಷ್ಟ್ಯ ನಿಷ್ಕ್ರಿಯವಾಗಿದೆ." }
} as const;
